import Head from "next/head"

export default function PageLayout({ children, title='Hidden Pokemon' }) {
  return (
    <>
      <Head>
        <title>{title}</title>
          <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {children}
    </>
  )
}